### ISSUE TITLE
求救求救

### ISSUE THREAD

**Issue by siri-FY** [BigShuiTai/FY3-Reader#1]
出现了这个错误是啥原因呢
Traceback (most recent call last):
  File "E:\FY3-Reader-master\FY3-Reader-master\test.py", line 36, in <module>
    mwri_l1.crop((25, 35, 135, 145))
  File "E:\FY3-Reader-master\FY3-Reader-master\fy3Reader\mwri_base.py", line 97, in crop
    yi, yj, xi, xj = self._get_indices(ll_box)
  File "E:\FY3-Reader-master\FY3-Reader-master\fy3Reader\mwri_base.py", line 52, in _get_indices
    yi, yj = np.amin(barrind_y), np.amax(barrind_y)
  File "<__array_function__ internals>", line 200, in amin
  File "D:\admin\envs\fy3d3d\lib\site-packages\numpy\core\fromnumeric.py", line 2946, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "D:\admin\envs\fy3d3d\lib\site-packages\numpy\core\fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by BigShuiTai** [comment]
```mwri_l1.crop((25, 35, 135, 145))```的含义是按照纬度25N\~35N，经度135E\~145E的范围对从文件读取到的数据进行裁剪。您可以检查一下裁剪的区域是不是在读取的文件的范围里。

**Comment by siri-FY** [comment]
我想在您代码的基础上把某一天的亮温数据合并到一起，然后处理成网格数据，您有什么思路吗，我实在是有点懵

**Comment by siri-FY** [comment]
img_extent = (135, 145, 20, 30)这个函数是干什么的呢
